region                 = "us-west-2"
state_bucket_name      = "lesson-8-9-tf-state-simakhin"
state_table_name       = "terraform-locks"
vpc_name               = "lesson-8-9-vpc"
vpc_cidr_block         = "10.0.0.0/16"
public_subnets         = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
private_subnets        = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]
availability_zones     = ["us-west-2a", "us-west-2b", "us-west-2c"]
enable_nat_gateway     = true
single_nat_gateway     = false
one_nat_gateway_per_az = true
ecr_repository_name    = "lesson-8-9-ecr"
scan_on_push           = true
cluster_name           = "lesson-8-9-cluster"