image:
  repository: 974436228692.dkr.ecr.us-west-2.amazonaws.com/lesson-8-9-ecr
  tag: 7

replicaCount: 2

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

service:
  type: LoadBalancer
  port: 8000
  targetPort: 8000

env:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  POSTGRES_DB: "myapp"
  POSTGRES_USER: "postgres"
  POSTGRES_HOST: "myapp-db.czo68eoemb6s.us-west-2.rds.amazonaws.com"
  POSTGRES_PORT: "5432"

secrets:
  DJANGO_SECRET_KEY: ""
  POSTGRES_PASSWORD: ""

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  host: oleksandr-simakhin.tech
  path: /
  pathType: Prefix
  tls: true
