image:
  repository: 974436228692.dkr.ecr.us-west-2.amazonaws.com/lesson-7-ecr
  tag: latest

replicaCount: 2

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

env:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  POSTGRES_DB: "mydatabase"
  POSTGRES_USER: "myuser"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"

secrets:
  DJANGO_SECRET_KEY: "placeholder-secret-key"
  POSTGRES_PASSWORD: "mypassword"

ingress:
  enabled: true
  className: nginx
  host: oleksandr-simakhin.tech
  path: /
  pathType: Prefix
  tls: true